Not Found: /static/admin/css/base.css
Not Found: /static/admin/css/dashboard.css
Not Found: /1
Internal Server Error: /1
Traceback (most recent call last):
  File "/Users/rmaja/virtualenvs/redirection/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rmaja/Dropbox/dev/proyectos/redirection/redirect/views.py", line 9, in redirector
    url = Page.objects.get(number=num)
  File "/Users/rmaja/virtualenvs/redirection/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/rmaja/virtualenvs/redirection/lib/python2.7/site-packages/django/db/models/query.py", line 345, in get
    clone = self.filter(*args, **kwargs)
  File "/Users/rmaja/virtualenvs/redirection/lib/python2.7/site-packages/django/db/models/query.py", line 691, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/Users/rmaja/virtualenvs/redirection/lib/python2.7/site-packages/django/db/models/query.py", line 709, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/Users/rmaja/virtualenvs/redirection/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1287, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
  File "/Users/rmaja/virtualenvs/redirection/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1314, in _add_q
    current_negated=current_negated, connector=connector)
  File "/Users/rmaja/virtualenvs/redirection/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1138, in build_filter
    lookups, parts, reffed_aggregate = self.solve_lookup_type(arg)
  File "/Users/rmaja/virtualenvs/redirection/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1076, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/Users/rmaja/virtualenvs/redirection/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1383, in names_to_path
    self.raise_field_error(opts, name)
  File "/Users/rmaja/virtualenvs/redirection/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1389, in raise_field_error
    "Choices are: %s" % (name, ", ".join(available)))
FieldError: Cannot resolve keyword 'number' into field. Choices are: all, android, id, ios, other
Not Found: /static/admin/css/base.css
Not Found: /static/admin/css/dashboard.css
